# Generated by Django 3.1.2 on 2020-12-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201220_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Notify Customer Email'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='notify_sms',
            field=models.BooleanField(default=True, verbose_name='Notify Customer SMS'),
        ),
    ]
