# Generated by Django 3.1.2 on 2020-12-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_auto_20201226_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authenticator'),
        ),
    ]
