# Generated by Django 3.1.2 on 2020-12-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201122_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='display_name',
            field=models.CharField(default='Permission Name', max_length=255, verbose_name='Permission Display Name'),
        ),
        migrations.AlterField(
            model_name='staffpermissionmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to='staff.staffmodel', verbose_name='Staff Id'),
        ),
    ]
