# Generated by Django 3.2.5 on 2022-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodel',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('management', 'Management'), ('admin', 'Admin'), ('teller', 'Teller')], max_length=25, verbose_name='Category'),
        ),
    ]
