# Generated by Django 3.1.2 on 2020-12-18 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeBranchModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Office Branch Id')),
                ('name', models.CharField(max_length=255, verbose_name='Office Branch Name')),
                ('office_type', models.CharField(choices=[(1, 'Headquarter'), (2, 'Regional Headquarter'), (3, 'Branch')], max_length=50, verbose_name='Office Type')),
            ],
            options={
                'db_table': 'bip_office',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nicname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'bip_state',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffOfficeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_asigned', models.DateTimeField(auto_now=True, verbose_name='Date Asigned')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.officebranchmodel', verbose_name='Office Location Id')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_office_id', to='staff.staffmodel', verbose_name='Staff Id')),
            ],
            options={
                'db_table': 'bip_staff_office',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='officebranchmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.statemodel', verbose_name='State Id'),
        ),
    ]
