# Generated by Django 3.1.2 on 2020-12-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebranchmodel',
            name='office_type',
            field=models.CharField(max_length=50, verbose_name='Office Type'),
        ),
    ]
