# Generated by Django 3.1.2 on 2020-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
        ('settings', '0002_auto_20201220_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffofficemodel',
            name='staff',
        ),
        migrations.AddField(
            model_name='staffofficemodel',
            name='staff',
            field=models.ManyToManyField(related_name='staff_office_id', to='staff.StaffModel', verbose_name='Staff Id'),
        ),
    ]
