# Generated by Django 3.1.2 on 2020-12-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
        ('settings', '0003_auto_20201220_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffofficemodel',
            name='staff',
        ),
        migrations.AddField(
            model_name='staffofficemodel',
            name='staff',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='staff_office_id', to='staff.staffmodel', verbose_name='Staff Id'),
            preserve_default=False,
        ),
    ]
