# Generated by Django 3.1.2 on 2020-12-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
        ('settings', '0004_auto_20201220_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffofficemodel',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_office_model', to='settings.officebranchmodel', verbose_name='Office Location Id'),
        ),
        migrations.AlterField(
            model_name='staffofficemodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_office_model', to='staff.staffmodel', verbose_name='Staff Id'),
        ),
    ]
