# Generated by Django 3.1.2 on 2020-12-26 14:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20201220_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Option Id')),
                ('name', models.CharField(max_length=255, verbose_name='Option Name')),
                ('value', models.CharField(max_length=50, verbose_name='Option Value')),
            ],
            options={
                'db_table': 'bip_option',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
