# Generated by Django 3.1.2 on 2020-11-22 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0003_authtokenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 11, 19, 19, 420114), verbose_name='Expires'),
        ),
    ]
