# Generated by Django 3.1.2 on 2020-12-07 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0004_auto_20201122_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 17, 42, 41, 311316), verbose_name='Expires'),
        ),
    ]
