# Generated by Django 3.1.2 on 2020-12-18 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0005_auto_20201207_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 12, 57, 44, 113178), verbose_name='Expires'),
        ),
    ]
