# Generated by Django 3.1.2 on 2020-12-20 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0008_auto_20201220_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 11, 21, 4, 607167), verbose_name='Expires'),
        ),
    ]
