# Generated by Django 3.1.2 on 2020-12-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0010_auto_20201220_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 11, 36, 6, 484075), verbose_name='Expires'),
        ),
    ]
