# Generated by Django 3.1.2 on 2020-12-20 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0011_auto_20201220_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 13, 5, 13, 672279), verbose_name='Expires'),
        ),
    ]
