# Generated by Django 3.1.2 on 2020-12-26 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0012_auto_20201220_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 11, 34, 53, 905251), verbose_name='Expires'),
        ),
    ]
