# Generated by Django 3.1.2 on 2020-12-26 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0013_auto_20201226_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 14, 22, 1, 920338), verbose_name='Expires'),
        ),
    ]
