# Generated by Django 3.1.2 on 2020-12-26 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0014_auto_20201226_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 15, 26, 36, 505291), verbose_name='Expires'),
        ),
    ]
