# Generated by Django 3.1.2 on 2021-01-03 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0015_auto_20201226_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 2, 35, 3, 480503), verbose_name='Expires'),
        ),
    ]
