# Generated by Django 3.1.2 on 2021-01-07 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bipnet_auth', '0017_auto_20210105_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 13, 59, 7, 860554, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
