# Generated by Django 3.1.2 on 2020-12-26 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20201220_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStandingsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Balance')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'db_table': 'bip_account_standings',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CentralAccountModel',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer.customermodel', verbose_name='Customer')),
                ('savings_account_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Savings Account Balance')),
                ('target_savings_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Traget Savings Balance')),
                ('fixed_deposit_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Fixed Deposit Balance')),
                ('activate_minimum_balance', models.BooleanField(verbose_name='Activate Minimum Banlnce')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'db_table': 'bip_central_account',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
