# Generated by Django 3.1.2 on 2020-12-26 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
        ('customer', '0002_auto_20201220_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsRecordModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Transaction Id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Transaction Amount')),
                ('transaction_type', models.CharField(max_length=10, verbose_name='Transaction Type')),
                ('channel', models.CharField(max_length=15, verbose_name='Transaction Channel')),
                ('status', models.CharField(max_length=15, verbose_name='Transaction Status')),
                ('narration', models.CharField(max_length=15, verbose_name='Narration')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='New Balance')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='savings_record_approve', to='staff.staffmodel', verbose_name='Approved By')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer')),
                ('initialized_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='savings_record_initialize', to='staff.staffmodel', verbose_name='Initialized By')),
            ],
            options={
                'db_table': 'bip_savings_record',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
