# Generated by Django 3.1.2 on 2021-01-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201226_1511'),
        ('transaction_manager', '0002_auto_20201226_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsrecordmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer'),
        ),
    ]
