# Generated by Django 3.1.2 on 2021-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_manager', '0003_auto_20210103_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsrecordmodel',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='New Balance'),
        ),
    ]
