# Generated by Django 3.1.2 on 2021-01-07 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201226_1511'),
        ('staff', '0003_auto_20201207_1727'),
        ('transaction_manager', '0004_auto_20210105_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDepositOutflowModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Transaction Id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Transaction Amount')),
                ('channel', models.CharField(max_length=15, verbose_name='Transaction Channel')),
                ('status', models.CharField(max_length=15, verbose_name='Transaction Status')),
                ('narration', models.CharField(max_length=40, verbose_name='Narration')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='New Balance')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixed_deposit_outflow_approve', to='staff.staffmodel', verbose_name='Approved By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer')),
            ],
            options={
                'db_table': 'bip_fixed_deposit_outflow',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FixedDepositModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Transaction Id')),
                ('reference_id', models.CharField(max_length=15, unique=True, verbose_name='Reference Id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Investment Amount')),
                ('amount_thread', models.TextField(verbose_name='Amount Thread for Deposits')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate')),
                ('upfront_interest', models.BooleanField(default=False, verbose_name='Upfront Interest')),
                ('interest_accrued', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Interest Accrued')),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Interest at Maturity')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Net Amount')),
                ('status', models.CharField(max_length=15, verbose_name='Fixed Deposit Status')),
                ('narration', models.CharField(max_length=40, verbose_name='Narration')),
                ('duration', models.IntegerField(max_length=5, verbose_name='Investment Duration')),
                ('investment_date', models.DateField(verbose_name='Investment Date')),
                ('maturity_date', models.DateField(verbose_name='Investment Date')),
                ('withholding_tax', models.BooleanField(verbose_name='Withholding Tax')),
                ('pre_liquidated', models.BooleanField(default=False, verbose_name='Pre-Liquidated')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixed_deposit_approve', to='staff.staffmodel', verbose_name='Approved By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer')),
                ('initialized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixed_deposit_initialize', to='staff.staffmodel', verbose_name='Initialized By')),
            ],
            options={
                'db_table': 'bip_fixed_deposit',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
