# Generated by Django 3.1.2 on 2021-01-08 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201207_1727'),
        ('customer', '0004_auto_20201226_1511'),
        ('transaction_manager', '0005_fixeddepositmodel_fixeddepositoutflowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDepositRecordModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Transaction Id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Transaction Amount')),
                ('transaction_type', models.CharField(max_length=10, verbose_name='Transaction Type')),
                ('channel', models.CharField(max_length=15, verbose_name='Transaction Channel')),
                ('status', models.CharField(max_length=15, verbose_name='Transaction Status')),
                ('narration', models.CharField(max_length=40, verbose_name='Narration')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='New Balance')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixed_deposit_outflow_approve', to='staff.staffmodel', verbose_name='Approved By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer')),
            ],
            options={
                'db_table': 'bip_fixed_deposit_record',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='FixedDepositOutflowModel',
        ),
    ]
