# Generated by Django 3.1.2 on 2021-01-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_manager', '0006_auto_20210108_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddepositmodel',
            name='reference_id',
        ),
    ]
