# Generated by Django 3.2.5 on 2022-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_manager', '0008_auto_20210111_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrecordmodel',
            name='drop_date',
            field=models.DateField(verbose_name='Drop Date'),
        ),
        migrations.AlterField(
            model_name='interestrecordmodel',
            name='withholding_tax',
            field=models.BooleanField(verbose_name='Withholding Tax')

            
        ),
    ]
